### ISSUE TITLE
Error on pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by joereynolds** [hotshot07/whatsapp_analyser#1]
It fails when trying to install the `wordcloud` module. It looks like it's because it's an absolute path from your own desktop

```
Processing /Users/hotshot07/Desktop/github/whatsapp_analyser/word_cloud
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/Users/hotshot07/Desktop/github/whatsapp_analyser/word_cloud'
```

Also the `word_cloud` directory itself is empty?

**Comment by hotshot07** [comment]
Oh it worked on my mac, I'll fix it asap

**Comment by hotshot07** [comment]
I changed the requirements file, so now it'll hopefully work. While testing it might've worked as it was referencing to a directory on my mac. Thank you

**Comment by joereynolds** [comment]
No problem, that fixes that issue but then another issue rears its head. I'll open up a separate issue!
